defmodule LockScreenQRCodeWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :lock_screen_qr_code

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_lock_screen_qr_code_key",
    signing_salt: "c09KWWAh",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Add a specific plug for the generated QR code images - this needs to come BEFORE the router
  plug Plug.Static,
    at: "/generated",
    from: {:lock_screen_qr_code, "priv/static/generated"},
    gzip: false,
    only: ~w(*.png *.jpg *.jpeg *.gif *.webp),
    cache_control_for_etags: "public, max-age=86400"

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :lock_screen_qr_code,
    gzip: not code_reloading?,
    only: LockScreenQRCodeWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :lock_screen_qr_code
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug LockScreenQRCodeWeb.Router
end
